DARWIN: Replace afs_osi_cred by allocated ucred
Building the current version of OpenAFS on macOS Monterey arm64 results
in the following error:

 error: globals with authenticated null values are currently unsupported
 afs_ucred_t afs_osi_cred;

To avoid this problem, replace the global in question by a pointer to a
dynamically allocated afs_osi_cred (afs_osi_credp). Alternately, we
could duplicate the current user's credential (like commit f40f466c7f).
Unfortunately, kauth_cred_create() is not well documented and calling it
resulted in unexplained system crashes.

Change-Id: Ied2df7590e4e671ce2643669c83ee0e4b2a97cd1